name: build

on: [push]

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
#    - name: Build fat jars
#      run: ./gradlew shadowJar
#    - name: Move jars
##      run: ls -la
#      run: mkdir shadowJars && mv build/libs/imgui*.jar shadowJars
#    - uses: actions/upload-artifact@v1
#      with:
#        name: ImGui linux artifacts
#        path: 'shadowJars'

  windows: 
    name: 'Windows'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Build with Gradle
        run: .\gradlew.bat build
#      - name: Build fat jars
#        run: ./gradlew shadowJar
#      - name: Move jars
#        run: mkdir shadowJars; mv build/libs/imgui*.jar shadowJars
#      - uses: actions/upload-artifact@v1
#        with:
#          name: ImGui windows artifacts
#          path: 'shadowJars'
                
  mac: 
    name: 'Mac OS'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
#      - name: Build fat jars
#        run: ./gradlew shadowJar
#      - name: Move jars
#        run: mkdir shadowJars && mv build/libs/imgui*.jar shadowJars
#      - uses: actions/upload-artifact@v1
#        with:
#          name: ImGui macOS artifacts
#          path: 'shadowJars'
